import React from "react";
import Image from "next/image";
import Container from "../Container";
import SectionTitle from "../SectionTitle";
import Card from "../Cards/Card";
import { ColumnImageProps } from "@/types";
import { columns } from "@/constants";

export default function Rarity() {
  return (
    <section className="" id="rarity">
      <Container>
        <Card className="">
          <div className="">
            <SectionTitle>Rarity</SectionTitle>
            <p>
              Each NFT is algorithmically generated by combining 170+ unique
              traits with varying rarity across categories.
            </p>
          </div>

          <div className="">
            {columns.map(({ name, image, items }) => (
              <ColumnImage
                key={`column-${name}`}
                name={name}
                items={items}
                image={image}
              />
            ))}
          </div>
        </Card>
      </Container>
    </section>
  );
}

const ColumnImage = ({ name, image, imageAlt, items }: ColumnImageProps) => {
  return (
    <div className="">
      <p className="">{name}</p>

      <div className="">
        {items?.map(({ boldText, title }, index) => (
          <div key={`item-${index}`} className="">
            <p className="">{boldText}</p>
            <p>{title}</p>
          </div>
        ))}

        <div className="">
          {image && (
            <div className="">
              <Image
                src={image || "No Image Provided"}
                alt={imageAlt || "No Alt Provided"}
                fill
              />
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
