import type { Metadata } from "next";
import { Space_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SkipToButton from "@/components/SkipToButton";

const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-space-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={spaceMono.variable}>
        <SkipToButton url="#main" text="Content" />

        <SkipToButton url="#footer" text="Footer" />
        <Header />

        <main id="main">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
